version: '3.9'

#`$> docker compose up`

#To enter the MongoShell. Open a new terminal and run: `mongosh`

services:
    mongodb:
        image: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: mydb
            #MONGO_INITDB_ROOT_USERNAME: root
            #MONGO_INITDB_ROOT_PASSWORD: password
            #MONGO_INITDB_DATA: /docker-entrypoint-initdb.d/init.js
        command: mongod --bind_ip_all --replSet rs0; sleep 5; mongosh --eval "rs.initiate()"