name: openral_mongodb
description: Implementation of the RalRepositories of openral-core with MongoDB
version: 1.0.0
repository: https://github.com/AndyPermaRobotics/openral-mongodb

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  mongo_dart: ^0.9.1
  openral_flutter: 
    git: 
        url: git@github.com:AndyPermaRobotics/openral-core.git
        path: flutter/openral_flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
